### ISSUE TITLE
First keypress ignored since latest update

### ISSUE THREAD

**Issue by amity** [sspanak/tt9#468]
Since updating to 28.0, my first keypress is consistently ignored when navigating to a new input. 

Previous/expected behavior: After navigating to a text chat or note, pressing "2->3->8" would add 3 letters, like "bet", etc.

New erroneous behavior: After navigating to a text chat or note, pressing "2->3->8" ignores the initial 2, inputting only the latter 3 and 8, suggesting "ev".

This happens reliably across all apps -- as a workaround for now I've started just pressing 0 when navigating to a new app, but it's rather annoying to do every time I want to type something, so I'll likely be downgrading to a previous version.

**Comment by amity** [comment]
Looks like this may be a duplicate of https://github.com/sspanak/tt9/issues/435 -- not certain, but seems like I may have been on v26 until this update. The trade-offs make sense, though it would be nice to potentially be able to have a toggle for this in settings (personally would _much_ rather not have to hit an extra button every time that I want to type).

**Comment by sspanak** [comment]
There was indeed a problem in v27.0, but it was fixed in v28.0. There shouldn't be any significant differences between versions 26 and 28. #435 concerns mostly customized Android versions, like the ones used on Sonim and Kyocera phones.

What you describe is certainly not intended. I need to know a couple of things to help me understand what's wrong.

1. I am able to replicate what you describe only by going to some application where I can type, then launch the TT9 settings, then go back to the previous app. At the point, the first press of keys 2 through 9 is ignored. However, 0 and 1 do work. Is this what you are experiencing?
2. Could you provide examples of popular applications where I can test? Does it happen if Chrome or Firefox, or any widely used instant messaging app?
3. When a text field comes into focus, does TT9 UI appear right away or when you press a key for the first time?
4. Does it happen if you erase all the text and start typing again?

**Comment by amity** [comment]
Thanks for the response -- hopefully point 5 is correct, I'll upgrade to v29 once it populates to F-Droid and report back then! :)

**Comment by sspanak** [comment]
@amity, are you still experiencing the bug? I believe I've fixed it a long time ago. With v31.0 already on F-droid and no more feedback, I feel like it's time to close this issue.

**Comment by amity** [comment]
I've been having issues with updating via F-Droid, so I'm on v29 and am still experiencing it but unfortunately can't verify whether it's fixed. Probably safe to declare it resolved and if I'm able to update I can bring it up again!

**Comment by sspanak** [comment]
@amity, thanks for coming back to the bug after all.

If you are having trouble with F-droid, try downloading the APK [from here](https://github.com/sspanak/tt9/releases/latest). The Github and the F-droid versions are now equivalent, which means you will be able to upgrade from either source in the future.
