### ISSUE TITLE
Unable to switch between predictive text and letters and numbers

### ISSUE THREAD

**Issue by berger321** [sspanak/tt9#92]
On qin f21 pro when some apps are opened, text input defaults to letters and the keyboard is unable to switch back to predictive text afterwards.

**Comment by sspanak** [comment]
Could you please provide a more specific example? It is difficult to tell what could be wrong.

Have in mind in some special-purpose fields, for example password fields, Predictive mode is intentionally disabled. But as soon as you go another field, you should be able to select it again.

**Comment by berger321** [comment]
Sure! So it mainly seems to happen in any browser app I try. At the moment I'm using firefox focus. If I use the traditional t9 ime keyboard from the play store it will still kick me into letters mode anyway but i am able to cycle back through to predictive. Using your tt9, it kicks me to letters as well but it will only let me cycle between letters, capitals and numbers and not return to predictive. This sometimes messes up the keyboard in other apps afterwards and I have a hard time getting it to return to predictive but If i reset the app and reload the dictionary it will work or sometimes I can get away with mashing the hash key.

**Comment by sspanak** [comment]
Oh, if it is Firefox then I know what you mean. What you experience is the same as #81 and it is already fixed. It's only that I haven't created a new release yet, but I would like to fix #91 too, before doing so.

If you are in 123 or ABC mode, there is no need to reload the dictionary. Just use #-key to go back to Predictive mode. Changing the mode is indeed what it is meant to do. I understand it may feel unusual if your previous experience was with Motorola or Sony Ericsson. 

Either way, check out all the hotkeys in [the user manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#hotkeys) for more info.

**Comment by berger321** [comment]
Ahh sorry, I had a look through the issues and I completely missed this somehow. That's fair enough about not entering predictive mode on urls, passwords etc but I agree it would be useful to have an email in your personal dictionary. 

There is still an issue though relating to this I think. If I search in the url bar using just letter mode and without trying to change the mode with the #  I can then type within a webpage afterwards in predictive text just fine. The problem is that if in the url bar you use the # key to cycle through the different modes and it loops back around past where predictive would have been, it then stops you from being able to change back to predictive even in the fields that it worked in before and it will only let you switch between numbers and letters. 

I guess it's not really an issue as long as you don't switch modes in the url bar but sometimes you need to enter numbers more quickly for example. Also if you did try to switch by accident then you would be stuck without predictive.

Thanks for taking the time! I've only just really figured out what was actually going on.

**Comment by berger321** [comment]
Ahh sorry, I had a look through the issues and I completely missed this somehow. That's fair enough about not entering predictive mode on urls, passwords etc but I agree it would be useful to have an email in your personal dictionary. 

I realized what was happening. I was trying to change to predictive mode in the url bar and afterward, in normal text fields it was still on numbers or letter mode. I then tried to change it by pressing the # key but it didn't work some of the time because I tried to do it while typing which just kept me going between capitals and letters and numbers. After clearing the field I can switch back to predictive. 

It makes me wonder though. It would be really useful to have a little indicator bubble momentarily pop up when you change modes to tell you which one you are in. I know the original implementation didn't have this but I've tried a couple of t9 keyboards that do and it's very helpful. Otherwise, you need to either keep track of the mode you are in in your head or test it out with some typing (Which was the cause of my troubles)

Anyway, thanks for taking the time! I feel a bit stupid that I've only just really figured out what was actually going on.

I've attached a video showing the indicator bubbles on the other keyboard if you were interested!

https://user-images.githubusercontent.com/116718085/198404819-dcd85a4c-5c8f-4e5a-88dc-8700e299351c.mp4

**Comment by sspanak** [comment]
Well, there is a permanent indicator at the top that shows the current mode.
![tt9-ab](https://user-images.githubusercontent.com/27846105/198527477-03514d08-fa40-4e10-ab6e-370afdc0f833.png)
![tt9-predictive](https://user-images.githubusercontent.com/27846105/198527492-e3c7360e-540e-442f-818f-92d6b8b08a14.png)
![tt9-123](https://user-images.githubusercontent.com/27846105/198527501-487778f8-1f72-4752-a67c-e1222d54a5f9.png)

Adding a popup is certainly possible and easy to do, but it didn't seem so useful in comparison to the permanent indicator, so I never did it.

**Comment by berger321** [comment]
Oh wow I feel like such a fool! I never actually noticed that. Yes, you're right the permanent indicator makes the popup one redundant, although maybe it is slightly more intuitive. Thanks!
